### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by drforester** [chrhenning/hypercl#1]
First, thanks for sharing this repository. Reading the paper made me want to immediately try the code.
Not knowing what versions of software you used, I made the virtual Python environment:
Python 3.7.5
PyTorch 1.3.1
TensorBoard 1.14.0

When trying to train the cifar example via

```
$ pycl train_resnet.py --use_adam --custom_network_init --plateau_lr_scheduler --lambda_lr_scheduler
```

I get the following error:

AttributeError: 'SummaryWriter' object has no attribute 'add_hparams'

I suspect that I could avoid this TensorBoard error by using the same software versions as the authors. Could I know the requirements of this repository?

Thanks for any help on this.

**Comment by chrhenning** [comment]
Hey,

Thanks for your request. I am currently out of office, but I will take care of it soon. In the meantime, I assume that the environment provided with our new repository works just as well

https://github.com/mariacer/cl_in_rnns

Best,
Christian

**Comment by drforester** [comment]
I wasn't aware that you have a new repository; thanks for letting me know. I'll start working with the latest code and close this issue.
