### ISSUE TITLE
dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by bjzhb666** [chrhenning/hypercl#3]
When I get documents using $make html, I face this problem and can not get any HTML in my project. How can I fix it? Thanks!
![image](https://user-images.githubusercontent.com/71651717/148525827-9aaa20cb-08cb-4326-b8ea-1df39811b78a.png)

**Comment by chrhenning** [comment]
Hey, I cannot reproduce this error. I quickly googled it and it could be a problem with your `torch` installation. Though, if you want, you can contact me via email henningc@ethz.ch and I'll directly send the compiled documentation to you.

Best, Christian

**Comment by bjzhb666** [comment]
Thanks for your quick reply. When I used my terminal directly (at first in Pycharm), I could get the HTML although the warnings still exist.
