### ISSUE TITLE
Confusing Experiment Result 

### ISSUE THREAD

**Issue by bjzhb666** [chrhenning/hypercl#4]
Hi! Thanks for your great work!!!

When I ran the Split MNIST experiment with HNET+ENT in CL 2 and CL 3 (Using the command in readme $ python train_splitMNIST.py --infer_task_id --infer_with_entropy --cl_scenario 2/3).
I got the result like this. (from the performance_overview.txt) 

**My question is why the acc of the last task is only 6.3540% (Even the acc_during is 6.3540%), as a binary classification problem, random selection can get about 50%. 
Another problem is why the acc (acc_after) of task1 is much higher than others. If there is a catastrophic forgetting, the acc of task5 should be the highest. But in my result, the acc of task5 is the lowest(6.3540%). 
I found the overall_task_infer_accuracy is the same as acc_after_list tensor, is this a coincidence?
How do you get your acc_after_mean result reported in your paper? You got 69.48 ± 0.80, but I just got 50.99 (just like a random selection). **

In CL3 :
acc_after_list tensor(99.7636, device='cuda:2') tensor(62.9285, device='cuda:2') tensor(54.0555, device='cuda:2') tensor(31.8731, device='cuda:2') tensor(6.3540, device='cuda:2')
acc_during_list tensor(99.9527, device='cuda:2') tensor(72.2821, device='cuda:2') tensor(55.6030, device='cuda:2') tensor(31.7221, device='cuda:2') tensor(6.3540, device='cuda:2')
acc_after_mean 50.994938
acc_during_mean 53.182766
overall_task_infer_accuracy_list tensor(99.7636, device='cuda:2') tensor(62.9285, device='cuda:2') tensor(54.0555, device='cuda:2') tensor(31.8731, device='cuda:2') tensor(6.3540, device='cuda:2')
acc_task_infer_mean 50.994938
num_train_iter 2000
num_weights_class_net 478410.000000
num_weights_rp_net 690684.000000
num_weights_rp_hyper_net 552712.000000
num_weights_class_hyper_net 465672.000000
compression_ratio_class 0.973374
compression_ratio_rp 4.061550

In CL2, I got similar results as the paper, but the acc of the last task is still the lowest and the acc of task1 is the highest. I have the same confusions as CL3.

**Comment by chrhenning** [comment]
Hey,

thanks for the question. SplitMNIST in CL3 is not a binary classification problem, but a 10-way classification problem. So, it seems as if task-inference (which is entropy-based in your case), fails for the last task. If the wrong task is inferred, the prediction is wrong, no matter what the prediction is.

The effect of catastrophic forgetting on the result heavily depends the strength of the regularizer (most easily to see in CL1 experiments). A too strong reg, doesn't allow forgetting, but hinders learning new things. But the CL3 accuracy depends even more on the task inference performance, whose outcome is hard to interpret for entropy-based task inference (see also our work on uncertainty-based task inference: https://github.com/chrhenning/posterior_replay_cl)

> I found the overall_task_infer_accuracy is the same as acc_after_list tensor, is this a coincidence?

This is to be expected, as the individual split MNIST tasks (binary classification) are so simple, that they are usually solved to (close to) 100% accuracy.

> How do you get your acc_after_mean result reported in your paper? You got 69.48 ± 0.80, but I just got 50.99 (just like a random selection). 

I currently can't run the code, but you could try running 10 random seeds and see if your low performance still persists. Maybe you just had bad luck with the random seed.

Hope this answers your questions.

Best, Christian

**Comment by bjzhb666** [comment]
Thanks for your quick reply and clear explanation! I have already understood all the questions.
About the my last question, I changed the random seed and the result improved(50.99 -> 57.87). Maybe I got a bad seed before.

**Comment by chrhenning** [comment]
Hey, maybe we also did a mistake when pushing the hyperparameters or something changed in the libraries in the meantime. In any case, the following link points to the exact same experiment, so you could also use this code

https://github.com/chrhenning/posterior_replay_cl/tree/master/probabilistic/prob_mnist#deterministic-task-specific-solutions

If you want to implement the method yourself (or integrate it into your own code base) I can recommend using our `hypnettorch` package

https://hypnettorch.readthedocs.io/en/latest/examples.html#continual-learning-with-hypernetworks
